"""add skill prerequisites and quiz questions

Revision ID: 26dc3c70d98d
Revises: 8ddf9c7a540f
Create Date: 2026-09-26 21:35:12.128444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '26dc3c70d98d'
down_revision: Union[str, None] = '8ddf9c7a540f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('skills', sa.Column('prerequisites', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'prerequisites')
    op.drop_column('game_sessions', 'questions')
    # ### end Alembic commands ###
