"""add attachments

Revision ID: 272cc30b4cfc
Revises: 26dc3c70d98d
Create Date: 2026-09-26 21:42:34.321494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '272cc30b4cfc'
down_revision: Union[str, None] = '26dc3c70d98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_group_id'), 'attachments', ['group_id'], unique=False)
    op.add_column('chat_messages', sa.Column('attachment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'attachments', ['attachment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'attachment_id')
    op.drop_index(op.f('ix_attachments_group_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
