"""add skills table

Revision ID: 8ddf9c7a540f
Revises: 85fd8c6749c0
Create Date: 2026-09-26 01:00:45.286572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ddf9c7a540f'
down_revision: Union[str, None] = '85fd8c6749c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    # ### end Alembic commands ###
