"""trails

Revision ID: a1b2c3d4e5f6
Revises: 85dfb0cc275d
Create Date: 2026-09-27 18:58:44.151219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '85dfb0cc275d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('concept', sa.String(length=300), server_default='', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_skill_id'), 'questions', ['skill_id'], unique=False)
    op.create_table('topic_notes',
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('concepts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('progress', sa.String(length=40), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('topic_plans',
    sa.Column('source_ref', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_ref', 'version')
    )
    op.create_table('video_context',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('youtube_id', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_video_context_created_at'), 'video_context', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_context_youtube_id'), 'video_context', ['youtube_id'], unique=False)
    op.create_table('trails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trails_user_id'), 'trails', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trail_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('status', sa.String(length=12), server_default='importing', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_ref'), 'sources', ['source_ref'], unique=False)
    op.create_index(op.f('ix_sources_trail_id'), 'sources', ['trail_id'], unique=False)
    op.create_table('trail_topics',
    sa.Column('trail_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prerequisites_override', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('equivalent_to', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trail_id', 'skill_id')
    )
    op.add_column('skill_videos', sa.Column('youtube_id', sa.String(length=20), nullable=True))
    op.add_column('skill_videos', sa.Column('start_sec', sa.Integer(), nullable=True))
    op.add_column('skill_videos', sa.Column('end_sec', sa.Integer(), nullable=True))
    op.add_column('skill_videos', sa.Column('duration', sa.Integer(), nullable=True))
    op.alter_column('skill_videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_skill_videos_youtube_id'), 'skill_videos', ['youtube_id'], unique=False)
    op.add_column('skills', sa.Column('source_ref', sa.String(length=64), nullable=True))
    op.add_column('skills', sa.Column('plan_version', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skills', sa.Column('summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_skills_source_ref'), 'skills', ['source_ref'], unique=False)
    # ### end Alembic commands ###

    import re, uuid as _uuid
    conn = op.get_bind()
    list_re = re.compile(r"[?&]list=([A-Za-z0-9_-]+)")
    rows = conn.execute(sa.text(
        "SELECT DISTINCT v.user_id, s.id, s.label, s.source_url FROM skill_videos v JOIN skills s ON s.id = v.skill_id "
        "WHERE v.user_id IS NOT NULL ORDER BY v.user_id, s.id"
    )).fetchall()
    trails: dict = {}
    for user_id, skill_id, label, source_url in rows:
        if user_id not in trails:
            trails[user_id] = _uuid.uuid4()
            conn.execute(sa.text("INSERT INTO trails (id, user_id, title) VALUES (:id, :u, 'My first trail')"),
                         {"id": trails[user_id], "u": user_id})
        m = list_re.search(source_url or "")
        ref = m.group(1) if m else skill_id[:64]
        conn.execute(sa.text("INSERT INTO topic_plans (source_ref, version, method, title) VALUES (:r, 0, 'chunked', :t) "
                             "ON CONFLICT DO NOTHING"), {"r": ref, "t": label[:500]})
        conn.execute(sa.text("UPDATE skills SET source_ref = :r, plan_version = 0 WHERE id = :s"), {"r": ref, "s": skill_id})
        conn.execute(sa.text(
            "INSERT INTO sources (id, trail_id, kind, url, source_ref, plan_version, title, status) "
            "VALUES (:id, :t, :k, :url, :r, 0, :title, 'ready')"),
            {"id": _uuid.uuid4(), "t": trails[user_id], "k": "playlist" if m else "video",
             "url": source_url or "", "r": ref, "title": label[:500]})
        pos = conn.execute(sa.text("SELECT count(*) FROM trail_topics WHERE trail_id = :t"), {"t": trails[user_id]}).scalar()
        conn.execute(sa.text("INSERT INTO trail_topics (trail_id, skill_id, position) VALUES (:t, :s, :p)"),
                     {"t": trails[user_id], "s": skill_id, "p": pos})
    # Lessons that came from a playlist import become shared (no owner).
    conn.execute(sa.text(
        "UPDATE skill_videos SET user_id = NULL WHERE skill_id IN (SELECT id FROM skills WHERE source_url LIKE '%list=%')"
    ))
    conn.execute(sa.text(
        "UPDATE skill_videos SET youtube_id = substring(url from '[?&]v=([A-Za-z0-9_-]{11})') WHERE youtube_id IS NULL"
    ))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_source_ref'), table_name='skills')
    op.drop_column('skills', 'summary')
    op.drop_column('skills', 'position')
    op.drop_column('skills', 'plan_version')
    op.drop_column('skills', 'source_ref')
    op.drop_index(op.f('ix_skill_videos_youtube_id'), table_name='skill_videos')
    # user_id stays nullable: playlist lessons lost their owners on upgrade.
    op.drop_column('skill_videos', 'duration')
    op.drop_column('skill_videos', 'end_sec')
    op.drop_column('skill_videos', 'start_sec')
    op.drop_column('skill_videos', 'youtube_id')
    op.drop_table('trail_topics')
    op.drop_index(op.f('ix_sources_trail_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_ref'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_trails_user_id'), table_name='trails')
    op.drop_table('trails')
    op.drop_index(op.f('ix_video_context_youtube_id'), table_name='video_context')
    op.drop_index(op.f('ix_video_context_created_at'), table_name='video_context')
    op.drop_table('video_context')
    op.drop_table('topic_plans')
    op.drop_table('topic_notes')
    op.drop_index(op.f('ix_questions_skill_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
