"""skill intelligence

Revision ID: bf50225ce0ca
Revises: a1b2c3d4e5f6
Create Date: 2026-09-30 00:30:33.976421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bf50225ce0ca'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=150), server_default='', nullable=False),
    sa.Column('programme', sa.String(length=100), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('mode', sa.String(length=20), server_default='online', nullable=False),
    sa.Column('duration_hours', sa.Float(), server_default='1', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('competencies', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('sample', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_source'), 'courses', ['source'], unique=False)
    op.create_table('enrolments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='enrolled', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id')
    )
    op.create_index(op.f('ix_enrolments_user_id'), 'enrolments', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=300), server_default='', nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('competency_ids', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='processing', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_owner_id'), 'materials', ['owner_id'], unique=False)
    op.create_table('official_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=150), server_default='', nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=True),
    sa.Column('cadre', sa.String(length=40), server_default='', nullable=False),
    sa.Column('department', sa.String(length=150), server_default='', nullable=False),
    sa.Column('division', sa.String(length=150), server_default='', nullable=False),
    sa.Column('current_assignment', sa.String(length=300), server_default='', nullable=False),
    sa.Column('qualifications', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('experience_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('past_trainings', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.String(length=80), nullable=True),
    sa.Column('competency_ids', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ready', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), server_default='', nullable=False),
    sa.Column('source_ref', sa.String(length=100), server_default='', nullable=False),
    sa.Column('competency_id', sa.String(length=40), nullable=True),
    sa.Column('difficulty', sa.Integer(), server_default='2', nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_assessment_id'), 'attempts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='learner', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_assessment_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_table('assessments')
    op.drop_table('official_profiles')
    op.drop_index(op.f('ix_materials_owner_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_enrolments_user_id'), table_name='enrolments')
    op.drop_table('enrolments')
    op.drop_index(op.f('ix_courses_source'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
